#!/bin/ruby
require 'colorize'

binary = ARGV[0]


def tool()
   puts `figlet YOUPROTECT`.colorize(:red).bold
             puts "-"*65
             puts "        YOUPROTECT  -  Software Protection Checker (ELF/EXE 64-bit)".colorize(:light_blue).bold
             puts "                Developed by Rubal Sharma (YOU)".colorize(:red).bold
             puts "-" * 65
end


if binary.nil?
  puts "[-] Usage: youprotect <binary>".colorize(:red).bold
    exit
end

unless File.exist?(binary)
  puts "[-] Binary not found! Please specify the full path."
  exit
end


#Stripped_Check
def check_stripped_binary(binary)
  stripped = `file #{binary}`
  if stripped.include?('not stripped')
    puts "[-] Not Stripped"
     else
      puts "[+] Stripped Binary".colorize(:red).bold
     end
end



#Check_NX
def check_nx(binary)
  nx = `readelf -W -l #{binary} 2>/dev/null`
  if nx.match?(/GNU_STACK.*RWE/)
   puts "[-] NX Disabled"
  else
    puts  "[+] NX Enabled".colorize(:red).bold
  end
end


#Check_canary
def check_canary(binary)
  canary = `readelf -s #{binary} 2>/dev/null`
  if canary.include?("__stack_chk_fail")
    puts "[+] Canary Found (Enabled)".colorize(:red).bold
  else
    puts "[-] Canary Not Found (Disabled)"
  end
end


#Check_PIE
def check_pie(binary)
  pie = `readelf -h #{binary} 2>/dev/null`
  if pie.include?("DYN")
   puts "[+] PIE Enabled".colorize(:red).bold
  else
    puts "[-] PIE Disabled"
  end
end

#Check_relro
def check_relro(binary)
  program_headers = `readelf -l #{binary} 2>/dev/null`
  dynamic_section = `readelf -d #{binary} 2>/dev/null`

  if program_headers.include?("GNU_RELRO")
    if dynamic_section.include?("BIND_NOW")
      puts "[+] Full RELRO".colorize(:green).bold
    else
      puts "[+] Partial RELRO".colorize(:yellow).bold
    end
  else
    puts "[-] No RELRO".colorize(:red).bold
  end
end


#check dep_nx exe
def check_dep_nx(binary)
  dep_nx = `readpe #{binary} 2>/dev/null`
  if dep_nx.include?("IMAGE_DLLCHARACTERISTICS_NX_COMPAT")
    puts "[+] DEP (NX) Enabled".colorize(:red).bold
  else
    puts "[-] DEP (NX) NOT Enabled"
  end
end



#check safeSeh 32bit
def check_safeseh(binary)
  safe_seh = `readpe #{binary} 2>/dev/null`
  if safe_seh.include?("IMAGE_DLLCHARACTERISTICS_NO_SEH")
    puts "[-] SafeSEH Disabled: NO_SEH is set".colorize(:red).bold
  else
    puts "[+] SafeSEH Enabled: NO_SEH not set".colorize(:red).bold
  end
end


#check stack_cookies
def check_stack_cookies(binary)
  stack_cookies = `objdump -d #{binary} 2>/dev/null` 
  if stack_cookies.include?("__stack_chk_fail") 
    puts "[+] Stack Cookies Enabled (/GS)".colorize(:red).bold
  else
    puts "[-] Stack Cookies NOT Enabled"
  end
end


#check cfg
def check_cfg(binary)
  cfg = `readpe #{binary} 2>/dev/null`
  if cfg.include?("IMAGE_DLLCHARACTERISTICS_GUARD_CF") || cfg.include?("GuardFlags")
    puts "[+] Control Flow Guard (CFG) Enabled".colorize(:red).bold
  else
    puts "[-] CFG NOT Enabled"
  end
end



#check Aslr Compatible
def check_aslr_compatible(binary)
  aslr = `readpe #{binary} 2>/dev/null`
  if aslr.include?("IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE")
    puts "[+] ASLR Compatible".colorize(:red).bold
  else 
    puts "[-] ASLR Not Compatible"
  end
end

#Check IAT protection

def check_iat_protection(binary)
  iat = `readpe #{binary} 2>/dev/null`
  if iat.include?("IMAGE_DLLCHARACTERISTICS_NO_BIND")
    puts "[+] IAT (RELRO) Protection Enabled".colorize(:red).bold
  else
    puts "[-] IAT (RELRO) Protection Disabled"
  end
end

#check digital signature
def check_digital_signature(binary)
  digital_sign = `readpe #{binary} 2>/dev/null`
  if digital_sign.include?("Security Directory")
    puts "[+] Digitally Signed".colorize(:red).bold
  else
    puts "[-] No Digital Signature"
  end
end

tool()
puts ""
puts "[+] Analyzing File..............".colorize(:green)
sleep 2


detect = `file #{binary}`
if detect.include?('ELF') && detect.include?('64-bit')
puts "[*] File detected: Linux ELF 64 bit".bold
sleep 2
puts ""
puts "==========Checking LINUX Binary Protections=========="
sleep 1
check_stripped_binary(binary)
check_nx(binary)
check_canary(binary)
check_pie(binary)
check_relro(binary)
puts "========================================================"

 elsif  detect.include?('PE32+')
    puts "[*] File detected: Windows EXE 64 bit".bold
sleep 2
puts ""
puts "====== Windows protection check is sketchy — trust it like you trust public Wi-Fi======".colorize(:yellow)
sleep 1
check_dep_nx(binary)
check_stack_cookies(binary)
check_cfg(binary)
check_aslr_compatible(binary)
check_iat_protection(binary)
check_digital_signature(binary)
puts "================================================="

elsif detect.include?('PE32')
     puts "[*] File detected: Windows EXE 32 bit".bold
sleep 2
puts ""
puts "====== Windows protection check is sketchy — trust it like you trust public Wi-Fi======".colorize(:yellow)
sleep 1
check_dep_nx(binary)
check_stack_cookies(binary)
check_cfg(binary)
check_aslr_compatible(binary)
check_iat_protection(binary)
check_digital_signature(binary)
check_safeseh(binary)


  else
    puts "[-] Unsupported Binary Format".colorize(:red).bold
    exit
 end
